version: '3'

services:
  web:
    image: golang:latest
    container_name: goapp
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - gonetwork
    command: ["tail", "-f", "/dev/null"]

  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gomysqldb
      MYSQL_USER: gouser
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gonetwork

networks:
  gonetwork:
    driver: bridge

volumes:
  mysql-data:
